# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gob < Formula
  desc "Background job management for HUMANs and AGENTs"
  homepage "https://github.com/juanibiapina/gob"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/gob/releases/download/v2.0.2/gob_2.0.2_darwin_amd64.tar.gz"
      sha256 "67d1c0a9ae240ee91e4b9d96228490b50a066c281905ff8c77b1090e69dcae1c"

      def install
        bin.install "gob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/gob/releases/download/v2.0.2/gob_2.0.2_darwin_arm64.tar.gz"
      sha256 "efb5055f13747f301c7e699743009ffbe891147356fbb11083d19e5b5a8af36a"

      def install
        bin.install "gob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v2.0.2/gob_2.0.2_linux_amd64.tar.gz"
      sha256 "fb952f4e1249196778c397e924401165e79967948329f1c74022b3a0229235b7"
      def install
        bin.install "gob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v2.0.2/gob_2.0.2_linux_arm64.tar.gz"
      sha256 "70601f94b61a72cf8e957de1164960add4feb001a5f8adb0ece3539e0f3e6995"
      def install
        bin.install "gob"
      end
    end
  end
end
