# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gob < Formula
  desc "Background job management for HUMANs and AGENTs"
  homepage "https://github.com/juanibiapina/gob"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/gob/releases/download/v0.9.1/gob_0.9.1_darwin_amd64.tar.gz"
      sha256 "c5df6082b6ca1acc37323a882cc2acd18484f6d8ffb7c062fdb79a1591ab72e9"

      def install
        bin.install "gob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/gob/releases/download/v0.9.1/gob_0.9.1_darwin_arm64.tar.gz"
      sha256 "d2ef61a51965a0622c7fc5b3459776d7872c5117271393bc351d1ef64b25848c"

      def install
        bin.install "gob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v0.9.1/gob_0.9.1_linux_amd64.tar.gz"
      sha256 "865c4dfff9c08bea3e930e4c0f4c8f3664dea8a1b21212372f02de74b038e45c"
      def install
        bin.install "gob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v0.9.1/gob_0.9.1_linux_arm64.tar.gz"
      sha256 "dae92904e26d143fed3f993680f12ef8bb2b860f3ebd2bd109d3b8066af87fa7"
      def install
        bin.install "gob"
      end
    end
  end
end
