# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpli < Formula
  desc "MCP CLI - invoke MCP server tools from the command line"
  homepage "https://github.com/juanibiapina/mcpli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.2.0/mcpli_1.2.0_darwin_amd64.tar.gz"
      sha256 "c6c83e73973a2fd746facab30f3d2030f44a2adb56e4fb57592ca430448483a0"

      define_method(:install) do
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.2.0/mcpli_1.2.0_darwin_arm64.tar.gz"
      sha256 "ab7341d4e614b836825de539b7e615f0eee12dfe2bd5a8dddc8190807ae5f66a"

      define_method(:install) do
        bin.install "mcpli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.2.0/mcpli_1.2.0_linux_amd64.tar.gz"
      sha256 "a936d2bf064c0afa2062c0d78f65029799bd0c1b18ae8c127c5448ac5fd211fa"
      define_method(:install) do
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.2.0/mcpli_1.2.0_linux_arm64.tar.gz"
      sha256 "ccc162860c5baf97c6815ef57014ab61cb788b8226ccb83995d491e4cb0b0809"
      define_method(:install) do
        bin.install "mcpli"
      end
    end
  end
end
