# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpli < Formula
  desc "MCP CLI - invoke MCP server tools from the command line"
  homepage "https://github.com/juanibiapina/mcpli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.1.0/mcpli_1.1.0_darwin_amd64.tar.gz"
      sha256 "58595a5dd5757590362ca692db4fc7347e67daf9b966b1c8874e1b13d9f77587"

      def install
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.1.0/mcpli_1.1.0_darwin_arm64.tar.gz"
      sha256 "c883a59897bf0bd21dc962f9f27881bdcc546a4eb9f8686f853ec10f31561cb0"

      def install
        bin.install "mcpli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.1.0/mcpli_1.1.0_linux_amd64.tar.gz"
      sha256 "06faed02405782452fd2ce1d7f6849067c88d41cc7ed26de5dfc1b532089cc82"
      def install
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.1.0/mcpli_1.1.0_linux_arm64.tar.gz"
      sha256 "13b6fb959a56e997b1ac9c460db2fb52aa959211bd1dddab1257f33d5c2bbeb8"
      def install
        bin.install "mcpli"
      end
    end
  end
end
