# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpli < Formula
  desc "MCP CLI - invoke MCP server tools from the command line"
  homepage "https://github.com/juanibiapina/mcpli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.0.0/mcpli_1.0.0_darwin_amd64.tar.gz"
      sha256 "05eabda93971a5a93293ce9b34f978c3e8c3bfde14c7c8dfc866fc95d992af3e"

      def install
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.0.0/mcpli_1.0.0_darwin_arm64.tar.gz"
      sha256 "3c56b97036b6c2ae4a9dd0fa6458d0d8baf97b29fa27f21584641096277b38fa"

      def install
        bin.install "mcpli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.0.0/mcpli_1.0.0_linux_amd64.tar.gz"
      sha256 "28312cabd06cab591111bb00557c2f0ebba4bd45c7f7dee23727f3b968665865"
      def install
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.0.0/mcpli_1.0.0_linux_arm64.tar.gz"
      sha256 "5228316860b00140ebf7d52125537dd264a1bd01221690a9127aea43a579c335"
      def install
        bin.install "mcpli"
      end
    end
  end
end
