# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "A simple per-directory todo list"
  homepage "https://github.com/juanibiapina/todo"
  version "2.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/todo/releases/download/v2.9.0/todo_2.9.0_darwin_amd64.tar.gz"
      sha256 "905fe96a2ab48340263aceb59560a7dd4dce2e8ee93aedb7065bb976f3aed467"

      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/todo/releases/download/v2.9.0/todo_2.9.0_darwin_arm64.tar.gz"
      sha256 "72acc0f3c17310c7e995d38821d1e4315f7b077b2d7ddee6b36c28d6a382a587"

      define_method(:install) do
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/todo/releases/download/v2.9.0/todo_2.9.0_linux_amd64.tar.gz"
      sha256 "483ed7fd0efe19a5cca8c86dde3281b5d87da0b64c7d0018935af6ee346bf477"
      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/todo/releases/download/v2.9.0/todo_2.9.0_linux_arm64.tar.gz"
      sha256 "0370be48573df6254c3e9149eb771518ad68144b5f625e31d84457c269186fea"
      define_method(:install) do
        bin.install "todo"
      end
    end
  end
end
