# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "A simple per-directory todo list"
  homepage "https://github.com/juanibiapina/todo"
  version "2.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/todo/releases/download/v2.6.0/todo_2.6.0_darwin_amd64.tar.gz"
      sha256 "0f4abffb28aef50eb435f2c8c961132aee8e2507550ceac17d6a4d6c6a4fc56d"

      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/todo/releases/download/v2.6.0/todo_2.6.0_darwin_arm64.tar.gz"
      sha256 "b810b22d8c631508fa294a29f088d72a74c7f1f195d8bed7e5c36f5e6156d95a"

      define_method(:install) do
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/todo/releases/download/v2.6.0/todo_2.6.0_linux_amd64.tar.gz"
      sha256 "8d65a03ed2c6971c5287f139f2a963f92a15336209aebcc4456937723a8a78a6"
      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/todo/releases/download/v2.6.0/todo_2.6.0_linux_arm64.tar.gz"
      sha256 "3baf7d182d8fb8d3a21c9599b70dffee98a9b6d34f8a9af3bce52f6057f6edf6"
      define_method(:install) do
        bin.install "todo"
      end
    end
  end
end
