# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gob < Formula
  desc "Background job management for HUMANs and AGENTs"
  homepage "https://github.com/juanibiapina/gob"
  version "3.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/gob/releases/download/v3.7.1/gob_3.7.1_darwin_amd64.tar.gz"
      sha256 "8ad31e211bbf6a6c6f97216e9ec00c478049ec64fd80fcc85e5d97d096741004"

      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/gob/releases/download/v3.7.1/gob_3.7.1_darwin_arm64.tar.gz"
      sha256 "1ad401d3bbf601cd2e833eb67e708e46492a8de836f4b9637b45f34a3a329297"

      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v3.7.1/gob_3.7.1_linux_amd64.tar.gz"
      sha256 "90b4ceae0e0739ff03c23b25dc9981ccc6e587d85e59778b59fb1a0653427ef2"
      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v3.7.1/gob_3.7.1_linux_arm64.tar.gz"
      sha256 "13ddae0c7fd59d4906dd055a41702687e541db871ee8b58466e5f7911b309f7c"
      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
  end
end
