# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gob < Formula
  desc "Background job management for HUMANs and AGENTs"
  homepage "https://github.com/juanibiapina/gob"
  version "3.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/gob/releases/download/v3.8.0/gob_3.8.0_darwin_amd64.tar.gz"
      sha256 "1414618380629b08a29d992d2d4de5c706de8d12743bd6873f51ad813c4273ca"

      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/gob/releases/download/v3.8.0/gob_3.8.0_darwin_arm64.tar.gz"
      sha256 "f65f6bed1fcd53610b95eac29d731f3e903cb16f4182fb2fe210fa60c9162edc"

      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v3.8.0/gob_3.8.0_linux_amd64.tar.gz"
      sha256 "046aa8305b81ba1aaf11ba2be4e201756637123fe5e1cc7c45c4a45bd304ece4"
      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/gob/releases/download/v3.8.0/gob_3.8.0_linux_arm64.tar.gz"
      sha256 "91c4804763f90714a528f91c755b9ca05c2f5b338b105ddcd7fa6e16ff07abf9"
      define_method(:install) do
        bin.install "gob"
        bash_completion.install "completions/gob.bash" => "gob"
        zsh_completion.install  "completions/gob.zsh"  => "_gob"
        fish_completion.install "completions/gob.fish"
      end
    end
  end
end
