# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpli < Formula
  desc "MCP CLI - invoke MCP server tools from the command line"
  homepage "https://github.com/juanibiapina/mcpli"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.1/mcpli_1.3.1_darwin_amd64.tar.gz"
      sha256 "479d31ca9973ea230153e3749bf3217a26f0b37bff0cf40b6f7f2d4647ca57c3"

      define_method(:install) do
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.1/mcpli_1.3.1_darwin_arm64.tar.gz"
      sha256 "2e40e1fa3a02747a73bcd1e7363946fd289c4b498a6beb63ffc45662ebfaecb5"

      define_method(:install) do
        bin.install "mcpli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.1/mcpli_1.3.1_linux_amd64.tar.gz"
      sha256 "71a73bee681188bfd709ef5182b46df94c06f45d64c1fecd206c9c493c23224d"
      define_method(:install) do
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.1/mcpli_1.3.1_linux_arm64.tar.gz"
      sha256 "79461b96b1e6ea8e62842b6d81bbc3dfd9031ad85a9623179c266f52b864715c"
      define_method(:install) do
        bin.install "mcpli"
      end
    end
  end
end
