# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpli < Formula
  desc "MCP CLI - invoke MCP server tools from the command line"
  homepage "https://github.com/juanibiapina/mcpli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.0/mcpli_1.3.0_darwin_amd64.tar.gz"
      sha256 "f8c73360014111e0826f9f6388ea9055ad0282eeda8613960fc7fdd558784b8a"

      define_method(:install) do
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.0/mcpli_1.3.0_darwin_arm64.tar.gz"
      sha256 "8168508aeb9fcef89bd0e753516a93691db85e6ae87e3e8fccca80a6192df4d7"

      define_method(:install) do
        bin.install "mcpli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.0/mcpli_1.3.0_linux_amd64.tar.gz"
      sha256 "3291904f4475b28011ee0987de6f2ed3d3b4209b6d9e0dfdf6f3a1a8f435cdc2"
      define_method(:install) do
        bin.install "mcpli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/mcpli/releases/download/v1.3.0/mcpli_1.3.0_linux_arm64.tar.gz"
      sha256 "3a78208b8e95e1f4dfee9adfc2cb4e2158151557202aa46b6d0a2e8d5e2e14b8"
      define_method(:install) do
        bin.install "mcpli"
      end
    end
  end
end
