# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "A simple per-directory todo list"
  homepage "https://github.com/juanibiapina/todo"
  version "3.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juanibiapina/todo/releases/download/v3.3.0/todo_3.3.0_darwin_amd64.tar.gz"
      sha256 "a8b70fcb1d75e359121f6f66951d21777b68b15b705f2c0830c53af17b1c217d"

      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juanibiapina/todo/releases/download/v3.3.0/todo_3.3.0_darwin_arm64.tar.gz"
      sha256 "818bcc51718257ae9539c07c70dae0ed8af9dcb034ff2727e486c7f1e19b4ce4"

      define_method(:install) do
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/todo/releases/download/v3.3.0/todo_3.3.0_linux_amd64.tar.gz"
      sha256 "4163301d01f1239d281f68523b722ab3b0fcff5ae0cb3fb1106b2aa002141305"
      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juanibiapina/todo/releases/download/v3.3.0/todo_3.3.0_linux_arm64.tar.gz"
      sha256 "04adbac04ce8c0e6cd110cfbdd4e551e91c6a0cac3594b1be9168e7e7f693a7b"
      define_method(:install) do
        bin.install "todo"
      end
    end
  end
end
