#!/usr/bin/env bash

set -e

user="$1"
repo="$2"

usage() {
  echo "make-go-formula <user> <repo>"
  exit 1
}

if [ -z "$user" ]; then
  usage
fi

if [ -z "$repo" ]; then
  usage
fi

# Fetch latest version
VERSION=`curl -s https://api.github.com/repos/${user}/${repo}/releases/latest | jq -r .tag_name`
VERSION_NO_V="${VERSION#v}"

# Construct URLs
ARM64_FILE="${repo}_${VERSION_NO_V}_darwin_arm64.tar.gz"
AMD64_FILE="${repo}_${VERSION_NO_V}_darwin_amd64.tar.gz"
ARM64_URL="https://github.com/${user}/${repo}/releases/download/${VERSION}/${ARM64_FILE}"
AMD64_URL="https://github.com/${user}/${repo}/releases/download/${VERSION}/${AMD64_FILE}"
CHECKSUMS_URL="https://github.com/${user}/${repo}/releases/download/${VERSION}/checksums.txt"

# Download and parse checksums
CHECKSUMS=`curl -sL "${CHECKSUMS_URL}"`
ARM64_SHA256=`echo "$CHECKSUMS" | grep "${ARM64_FILE}" | cut -f 1 -d " "`
AMD64_SHA256=`echo "$CHECKSUMS" | grep "${AMD64_FILE}" | cut -f 1 -d " "`

# Get description
DESCRIPTION=`curl -s https://api.github.com/repos/${user}/${repo} | jq -r .description`

# Generate formula
cat > ${repo}.rb <<EOF
class ${repo^} < Formula
  desc '${DESCRIPTION}'
  homepage 'https://github.com/${user}/${repo}'
  version '${VERSION}'

  on_macos do
    on_arm do
      url '${ARM64_URL}'
      sha256 '${ARM64_SHA256}'
    end

    on_intel do
      url '${AMD64_URL}'
      sha256 '${AMD64_SHA256}'
    end
  end

  def install
    bin.install '${repo}'
  end
end
EOF

echo "Formula created: ${repo}.rb"
